version: '3.4'
services:
  jira:
    image: cptactionhank/atlassian-jira:latest
    restart: always
    links:
      - database
    volumes:
      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence:latest
    restart: always
    links:
      - database
    volumes:
      - confluence-data:/var/atlassian/confluence

  bitbucket:
    image: atlassian/bitbucket-server:latest
    restart: always
    links:
      - database
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket

  jira-service-desk:
    image: cptactionhank/atlassian-jira-service-desk:latest
    restart: always
    links:
      - database
    volumes:
      - jira-service-desk-data:/var/atlassian/application-data/jira-service-desk

  database:
    image: postgres:9.4
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - jira
      - confluence
      - bitbucket
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
volumes:
  jira-data:
  confluence-data:
  bitbucket-data:
  database-data:
  jira-service-desk-data:
